version: '3.8'
services:
  server:
    container_name: workfloe_server_prod
    restart: unless-stopped
    image: workfloe-server
    build:
      context: server
      target: production
      dockerfile: Dockerfile
    ports: 
      - 5001:5001
    networks:
      - shared-network
  client:
    container_name: workfloe_client_prod
    restart: unless-stopped
    image: workfloe-client
    build:
      context: client
      target: production
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    networks:
      - shared-network
    depends_on:
     - server
networks: 
  shared-network: